-- =============================================================================
-- Belpro — Initial Database Schema
-- Database: belpro
-- Runs at container init time as 01_schema.sql (after 00_extra_dbs.sh).
--
-- NOTE: Do NOT edit this file after the first container run.
--       All subsequent schema changes must go through Alembic migrations.
-- =============================================================================

-- Enable pgcrypto for UUID generation
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =============================================================================
-- SCHEMA: n8n
-- n8n manages its own tables within this schema.
-- We just ensure it exists so n8n can initialise cleanly.
-- =============================================================================
CREATE SCHEMA IF NOT EXISTS n8n;

-- =============================================================================
-- ENUMS
-- =============================================================================

CREATE TYPE entry_status AS ENUM (
    'pending_volunteer',   -- Waiting for volunteer to confirm
    'pending_manager',     -- Confirmed by volunteer, waiting for manager
    'approved',            -- Manager approved
    'rejected'             -- Manager rejected
);

-- =============================================================================
-- TABLE: managers
-- One manager per deployment (single-tenant).
-- =============================================================================
CREATE TABLE managers (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name          VARCHAR(100) NOT NULL,
    last_name           VARCHAR(100) NOT NULL,
    phone               VARCHAR(30)  NOT NULL UNIQUE,   -- WhatsApp number, international format
    email               VARCHAR(255) NOT NULL UNIQUE,
    ngo_name            VARCHAR(255) NOT NULL,
    ngo_street          VARCHAR(255) NOT NULL,
    ngo_postal_code     VARCHAR(4)   NOT NULL,          -- 4-digit Slovenian postal code
    ngo_city            VARCHAR(100) NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE managers IS 'Single NGO manager per deployment. One row expected.';
COMMENT ON COLUMN managers.phone IS 'WhatsApp number in international format, e.g. +38641123456';

-- =============================================================================
-- TABLE: volunteers
-- =============================================================================
CREATE TABLE volunteers (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name          VARCHAR(100) NOT NULL,          -- Used in informal WhatsApp messages
    last_name           VARCHAR(100) NOT NULL,          -- Used in formal documents and PDFs
    street              VARCHAR(255) NOT NULL,          -- Street name + house number
    postal_code         VARCHAR(4)   NOT NULL,          -- 4-digit Slovenian postal code
    city                VARCHAR(100) NOT NULL,
    emso                TEXT         NOT NULL,          -- EMŠO — AES-256 encrypted at application level
    phone               VARCHAR(30)  NOT NULL UNIQUE,   -- WhatsApp number, international format
    email               VARCHAR(255),                   -- For monthly PDF delivery (nullable)
    active              BOOLEAN      NOT NULL DEFAULT TRUE,
    registered_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    manager_id          UUID         NOT NULL REFERENCES managers(id) ON DELETE RESTRICT
);

COMMENT ON TABLE volunteers IS 'Registered volunteers. Soft-deleted via active=false.';
COMMENT ON COLUMN volunteers.emso IS 'EMŠO encrypted with AES-256 at application level before storage. Never store plaintext.';
COMMENT ON COLUMN volunteers.email IS 'Optional. Required for automatic monthly PDF delivery.';
COMMENT ON COLUMN volunteers.active IS 'False = soft-deleted. Never hard-delete volunteer records.';

CREATE INDEX idx_volunteers_manager   ON volunteers(manager_id);
CREATE INDEX idx_volunteers_active    ON volunteers(active);
CREATE INDEX idx_volunteers_phone     ON volunteers(phone);

-- =============================================================================
-- TABLE: log_entries
-- =============================================================================
CREATE TABLE log_entries (
    id                      UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    volunteer_id            UUID            NOT NULL REFERENCES volunteers(id) ON DELETE RESTRICT,

    -- Work details (extracted by AI from voice/text)
    entry_date              DATE            NOT NULL,   -- Date of the work, not submission date
    activity_description    TEXT            NOT NULL,   -- Cleaned/normalised description
    raw_transcript          TEXT,                       -- Original Whisper output, kept for audit
    hours                   NUMERIC(4,1)    NOT NULL,
    location                VARCHAR(255),               -- Extracted or inferred from transcript

    -- Workflow status
    status                  entry_status    NOT NULL DEFAULT 'pending_volunteer',

    -- Photo evidence (all nullable — photo is optional)
    photo_path              VARCHAR(500),               -- Relative path within api_photos volume
    photo_exif_timestamp    TIMESTAMPTZ,                -- Extracted from EXIF data
    photo_exif_lat          NUMERIC(10,7),              -- GPS latitude from EXIF
    photo_exif_lon          NUMERIC(10,7),              -- GPS longitude from EXIF

    -- Audit timestamps
    volunteer_confirmed_at  TIMESTAMPTZ,
    manager_approved_at     TIMESTAMPTZ,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE log_entries IS 'Individual volunteer work diary entries. Core audit trail.';
COMMENT ON COLUMN log_entries.entry_date IS 'The date work was performed, not when it was submitted.';
COMMENT ON COLUMN log_entries.raw_transcript IS 'Original Whisper output preserved for audit. May contain dialect/errors.';
COMMENT ON COLUMN log_entries.photo_path IS 'Relative path within the api_photos Docker volume. Null if no photo submitted.';

CREATE INDEX idx_entries_volunteer    ON log_entries(volunteer_id);
CREATE INDEX idx_entries_status       ON log_entries(status);
CREATE INDEX idx_entries_date         ON log_entries(entry_date);
CREATE INDEX idx_entries_location     ON log_entries(location);
CREATE INDEX idx_entries_created      ON log_entries(created_at);

-- Composite: most common dashboard query — volunteer + month
CREATE INDEX idx_entries_vol_date     ON log_entries(volunteer_id, entry_date);

-- Auto-update updated_at on row change
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_entries_updated_at
    BEFORE UPDATE ON log_entries
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- TABLE: monthly_reports
-- Tracks generated PDF reports for audit and re-delivery purposes.
-- =============================================================================
CREATE TABLE monthly_reports (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    volunteer_id    UUID        REFERENCES volunteers(id) ON DELETE RESTRICT,
                                -- NULL = consolidated manager report
    period_year     SMALLINT    NOT NULL,
    period_month    SMALLINT    NOT NULL CHECK (period_month BETWEEN 1 AND 12),
    pdf_path        VARCHAR(500) NOT NULL,              -- Relative path within api_pdfs volume
    generated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    sent_at         TIMESTAMPTZ                         -- NULL = not yet sent by email
);

COMMENT ON TABLE monthly_reports IS 'Tracks generated PDF reports. volunteer_id NULL = manager consolidated report.';
COMMENT ON COLUMN monthly_reports.volunteer_id IS 'NULL for the manager consolidated report covering all volunteers.';
COMMENT ON COLUMN monthly_reports.sent_at IS 'Timestamp of email delivery. NULL means not yet sent or manually downloaded.';

CREATE INDEX idx_reports_volunteer    ON monthly_reports(volunteer_id);
CREATE INDEX idx_reports_period       ON monthly_reports(period_year, period_month);

-- Prevent duplicate reports for the same volunteer+period
CREATE UNIQUE INDEX idx_reports_unique_vol_period
    ON monthly_reports(volunteer_id, period_year, period_month)
    WHERE volunteer_id IS NOT NULL;

-- Prevent duplicate consolidated reports for the same period
CREATE UNIQUE INDEX idx_reports_unique_consolidated_period
    ON monthly_reports(period_year, period_month)
    WHERE volunteer_id IS NULL;
